---
repos:

  # yaml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: ['-d {extends: relaxed, rules: {line-length: disable}}', '-s']

  # pre commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # yapf
  - repo: https://github.com/google/yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf

  # isort
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--line-length", "99", "-m", "5"]

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
          - "--max-complexity=6"
          - "--ignore=D100, D101, D102, D103, D104, W503, W504, E203, E126"
          - "--exclude=.git,__pycache__,tests,env,venv,build,sql.py"
